version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=msjinkitea@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=gcloud"
      - "--log.level=TRACE"
      - "--accesslog=true"
      - "--api.dashboard=true"
    environment:
      - GCE_PROJECT=neat-pagoda-446818-a2 # Google Cloud 프로젝트 ID
      - GCE_SERVICE_ACCOUNT_FILE=/dns-key.json # 서비스 계정 키 파일 경로
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-certificates:/letsencrypt"
      - "/home/jinkitea/dns-key.json:/dns-key.json:ro" # Google DNS 인증 키 마운트
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mydashboard.rule=Host(`traefik.devsketch.xyz`)"
      - 'traefik.http.routers.mydashboard.entrypoints=websecure'
      - "traefik.http.routers.mydashboard.service=api@internal"
      - "traefik.http.routers.mydashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.mydashboard.loadbalancer.server.port=8080"
    networks:
      - directory_DevSketch-Net

  backend:
    image: sensesis/devsketch:1.0.78  # 최신 이미지 태그 사용
    container_name: DevSketch-Backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - directory_DevSketch-Net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.devsketch.xyz`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

    command: >
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 600
    environment:
      RUNNING_IN_DOCKER: 'true'
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK_API_URL: ${DEEPSEEK_API_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FRONTEND_RESULT_URL: ${FRONTEND_RESULT_URL}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis:7.0
    container_name: DevSketch-Redis
    ports:
      - "6379:6379"
    networks:
      - directory_DevSketch-Net
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: DevSketch-RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    networks:
      - directory_DevSketch-Net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery_worker:
    image: sensesis/devsketch:1.0.78 # 최신 이미지 태그 사용
    container_name: DevSketch-Celery-Worker
    privileged: true
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    depends_on:
      - backend
      - rabbitmq
      - redis
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DEEPSEEK_API_URL: ${DEEPSEEK_API_URL}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      FRONTEND_RESULT_URL: ${FRONTEND_RESULT_URL}
    networks:
      - directory_DevSketch-Net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: Devsketch-Cadvisor
    ports:
    - "8081:8080"
    volumes:
      - /:/rootfs:ro #읽기 전용 데이터 - 루트 파일 시스템
      - /var/run:/var/run:rw #읽기 & 쓰기 - 런타임 데이터
      - /sys:/sys:ro  #읽기 전용 데이터 - 커널, 하드웨어, 드라이버 정보 등등
      - /var/lib/docker/:/var/lib/docker:ro #읽기 전용 데이터 - 도커 정보 데이터
    networks:
      - directory_DevSketch-Net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.devsketch.xyz`)"
      - "traefik.http.routers.cadvisor.entrypoints=websecure"
      - "traefik.http.routers.cadvisor.tls.certresolver=letsencrypt"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"

volumes:
  traefik-certificates:
    external: false
  redis_data:
  rabbitmq_data:
  grafana_data:

networks:
  directory_DevSketch-Net:
    name: directory_DevSketch-Net
    driver: bridge