version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=jinkitea@naver.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=gcloud"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.dashboard=true"
    environment:
      - GCE_PROJECT=neat-pagoda-446818-a2 # Google Cloud 프로젝트 ID
      - GCE_SERVICE_ACCOUNT_FILE=/dns-key.json # 서비스 계정 키 파일 경로
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-certificates:/letsencrypt"
      - "/home/jinkitea/dns-key.json:/dns-key.json:ro" # Google DNS 인증 키 마운트
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mydashboard.rule=Host(`traefik.devsketch.site`)"
      - 'traefik.http.routers.mydashboard.entrypoints=websecure'
      - "traefik.http.routers.mydashboard.service=api@internal"
      - "traefik.http.routers.mydashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.mydashboard.loadbalancer.server.port=8080"
    networks:
      - directory_DevSketch-Net

  backend:
    image: sensesis/devsketch:1.0.47  # 최신 이미지 태그 사용
    container_name: DevSketch-Backend
    restart: always
    env_file:
      - .env
    networks:
      - directory_DevSketch-Net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`devsketch.site`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

    command: >
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 120
    environment:
      RUNNING_IN_DOCKER: 'true'
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK_API_URL: ${DEEPSEEK_API_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FRONTEND_RESULT_URL: ${FRONTEND_RESULT_URL}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis:7.0
    container_name: DevSketch-Redis
    ports:
      - "6379:6379"
    networks:
      - directory_DevSketch-Net
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: DevSketch-RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - directory_DevSketch-Net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery_worker:
    image: sensesis/devsketch:1.0.47  # 최신 이미지 태그 사용
    container_name: DevSketch-Celery-Worker
    privileged: true
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    depends_on:
      - backend
      - rabbitmq
      - redis
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DEEPSEEK_API_URL: ${DEEPSEEK_API_URL}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      FRONTEND_RESULT_URL: ${FRONTEND_RESULT_URL}
    networks:
      - directory_DevSketch-Net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.routers.grafana.rule=Host(`grafana.devsketch.site`)
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - directory_DevSketch-Net



volumes:
  traefik-certificates:
    external: false
  redis_data:
  rabbitmq_data:
  grafana_data:

networks:
  directory_DevSketch-Net:
    name: directory_DevSketch-Net
    driver: bridge
