version: '3.8'

services:
  backend:
    container_name: DevSketch-Backend
    build:
      context: ../Backend
    volumes:
      - static_volume:/Backend/static
    env_file:
      - .env
    networks:
      - DevSketch-Net
    restart: always
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 300"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.${BASE_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=web,websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  redis:
    image: redis:7.0
    container_name: DevSketch-Redis
    networks:
      - DevSketch-Net
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: DevSketch-RabbitMQ
    networks:
      - DevSketch-Net
    restart: always

  celery_worker:
    build:
      context: ../Backend
    container_name: DevSketch-Celery-Worker
    command: celery -A config worker --loglevel=info
    depends_on:
      - backend
      - rabbitmq
      - redis
    env_file:
      - .env
    networks:
      - DevSketch-Net
    restart: always

  traefik:
    image: traefik:v2.9
    container_name: DevSketch-Traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${jinkitea@naver.com}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    env_file:
      - .env
    networks:
      - DevSketch-Net
    restart: always

volumes:
  static_volume:
  letsencrypt:

networks:
  DevSketch-Net:
    driver: bridge